# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1537b32fe945e3bd61ea54cf1e1d29adf000e437d9dd4cd524e252c90e29f9370763a108cf41f5eb961aa7bd2bc03946c075e250c84a15fb8f0ae55eed4041a6

test:
  secret_key_base: 52227d4d0f136a802e668431ab2d08758715956609a21696dacd714ae904ebd8679ea8d34e614ea9462f2e7877e1e02a4cba7cb0c317916d217fc8de5b4df5b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
